#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const target = join(root, 'src', 'version.ts');

const contents = `// Generated by scripts/sync-version.mjs. Do not edit by hand.
export const SDK_VERSION = '${version}';
`;

writeFileSync(target, contents);
console.log(`Synced ${target} → ${version}`);
